### ISSUE TITLE
合肥校区连接不上

### ISSUE THREAD

**Issue by luyi404** [elonzh/hfut#4]
一直出现这个问题
[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by earlzo** [comment]
这个包直至老版的教务系统, 是不是合肥校区不再使用了呢?

相关配置见: https://github.com/earlzo/hfut/blob/master/hfut/value.py

**Comment by lythings** [comment]
合肥校区目前使用的信息门户地址为 http://my.hfut.edu.cn/
与配置文件中的地址有所改变。

**Comment by earlzo** [comment]
这个包只支持老版的教务系统, 不支持信息门户, 看上去合肥和宣城都下线了老的教务系统

**Comment by lythings** [comment]
宣城校区不确定，之前使用文档中的例子。仍能爬取宣城校区18证件照，校区改为合肥之后提示连接不上，宣城校区却能够下载到。

**Comment by earlzo** [comment]
如果是学校下线了相关系统, 这边应该就无能为力了

**Comment by lythings** [comment]
现在通过信息门户登录本科教务之后的地址为
http://jxglstu.hfut.edu.cn/eams5-student/home

**Comment by earlzo** [comment]
不是一个系统了, 应该合肥校区没法使用了

**Comment by lythings** [comment]
好的，谢谢学长了。我自己去爬一下好了

**Comment by earlzo** [comment]
加油
